ref_param exception: "Dicts cannot contain references"
ref_param exception: "Dicts cannot contain references"
ref_param exception: "Dicts cannot contain references"
ref_param exception: "Invalid dict key: expected a key of type int or string, bool given"
dict(4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
elem_ref exception: "Dicts cannot contain references"
elem_ref exception: "Dicts cannot contain references"
elem_ref exception: "Dicts cannot contain references"
elem_ref exception: "Invalid dict key: expected a key of type int or string, bool given"
dict(4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
append_ref exception: "Dicts cannot contain references"
dict(4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
set_ref exception: "Dicts cannot contain references"
set_ref exception: "Dicts cannot contain references"
set_ref exception: "Dicts cannot contain references"
set_ref exception: "Invalid dict key: expected a key of type int or string, bool given"
dict(4) {
  [0]=>
  int(1)
  [1]=>
  int(2)
  [2]=>
  int(3)
  [3]=>
  int(4)
}
convert_with_ref exception: "Dicts cannot contain references"

Notice: Unable to unserialize: [D:2:{s:3:"foo";D:1:{s:1:"a";s:1:"b";}s:3:"bar";R:2;}]. Dicts cannot contain references. in %s on line 102
bool(false)
